### ISSUE TITLE
Mobs randomly teleport upwards when chasing the player

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#107]
If you anger a mob so it chases you, it sometimes randomly teleports upwards while doing so.
This is definitely the case for the stone monster and the sand monster in `mobs_animal`.
Just punch the monster on a flat world and run away and look what happens.

I have also observed this for numerous mobs in `mobs_mc`.

Testing environment:

* Minetest 0.4.16
* Minetest Game 0.4.16
* `mobs` d31010216ad2e707b811ebcb95bfe184190441b8
* `mobs_animal` 1561ec14477bb1663ebaaf4813b334e54d0ca193

A related issue is that zombies from `mobs_mc` fall through a 1-node thick floor sometimes when chasing you.

**Comment by tenplus1** [comment]
I've been testing for an hour now and cannnot get any monsters to randomly teleport up while being chased, although the mobs_mc does have some animation issues which causes jumpy animation that mobs_monsters does not...  I did however see the zombie fall through a 1 node thick floor but on mobs_monsters stone monsters and the like with similar settings did not?!

**Comment by tenplus1** [comment]
Fixed.

**Comment by Wuzzy2** [comment]
Sadly, no. Not fixed.

Tested with a stone monster on a flat world in Creative Mode. I just punched it with a shovel and quickly backd off. It took only a few seconds for the weird teleport bug to occour again.
I also just nuked `minetest.conf` beforehand, just in case.

* `mobs` bc13ef741022d61d75e5d2b5d8f01938931d8bf7
* `mobs_monster` `1561ec14477bb1663ebaaf4813b334e54d0ca193`
* `mobs_animal` `cadacac5aa399eeb55b51430456f36776ad6221c`

WTF? Why do I still have this bug?

**Comment by Wuzzy2** [comment]
Okay, some more details:
In `mobs_monster`, this appears to happen for stone monster, sand monster and dirt monster.
But it doesn't seem to happen for spider and lava flan and tree monster.

Also, when I say “teleporting”, I mean the mob just suddenly appears a short distance above the previous location. I also noted it's not just the model but the whole selection box which moves. So I guess we can safely discard the “broken model animation” hypothesis.

**Comment by tenplus1** [comment]
I know that the engine itself has issues with entity collision which results in entities (not just mobs) going through solid walls, so maybe it's related to that in some weird way as I dont see them teleporting a short distance up here (fixed 19th July 0.4.16 dev build)... also, are they walking OVER any specific node when they move up ? snow ? flowers etc.

**Comment by Wuzzy2** [comment]
No, they just walk over simple nodes, like “Dirt with Grass”.

Also, remember I only tested in MT 0.4.16, not in bleeding edge versions.

Do you care to point me to the offending MT commit / issue?

**Comment by Wuzzy2** [comment]
Still not fixed.

* `mobs`: 28dc0d8be5450ad5289c5b1053af83881ae1004c
* `mobs_animal`: `c1799f203cb1b0854df17d95e6a1ff4104559dfd`
* Minetest / Minetest Game: 0.4.16

Why is this issue still closed?

Here's a reliable way to reproduce this for me:

1. Build a 1×1 pathway made out of blocks (e.g. bronze block) in the sky
2. Spawn a dirt monster
3. Punch it so it starts chasing
4. Fly to the end of the platform, make sure the monster is still trying to follow you
5. The dirt monster should teleport a small distance above for no apparent reason in seemlingly random intervals

**Comment by Wuzzy2** [comment]
@tenplus1 Hmm, I guess I found the reason.

There are two `setpos` in the mod code. This one looks suspicious:

```
-- attempt to unstick mob that is "daydreaming"
self.object:setpos({
   x = s.x + 0.1 * (random() * 2 - 1),
   y = s.y + 1,
   z = s.z + 0.1 * (random() * 2 - 1)
})
```

And indeed, when I insert a debug output before this part, this is exactly what causes these weird teleportations!

What is the point of this code? Is there a reason for it? Because these random teleportations are so annoying! Whatever you attempt to fix or work around here, a plain `setpos` just seems wrong. There must be a better way.
