### ISSUE TITLE
Jump sound may be played many times in quick succession

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#139]
If you have a mob which jumps a lot and it gets stuck somewhere, you will hear the jumping sound very frequently which can be a bit annoying.

This is a problem in the `mobs_mc` mod, specifically, the slime mobs.

I suggest that Mobs Redo uses an internal cooldown timer for the jump sound. Maybe 0.5 to 1.0 seconds? So if the jump sound was played, it is guaranteed to not be played again for this mob before this short cooldown time has passed, even if the mob jumped again within this time. After the cooldown time is over, the next jump will have a sound again.

Note I only want the sound behaviour to be changed, not the jumping.

**Comment by tenplus1** [comment]
fixed.

**Comment by Wuzzy2** [comment]
No, this is not fixed. I still have mobs which play the jump sound like crazy.

Proof: Spawn a slime from `mobs_mc`, attack it until only a few (e.g. 2) tiny slimes are left. You will still hear a lot of jump sound spam, especially when one slime is on top of another.

Tested in: fc40d8d7e0b375098c9148bcbf873e640ccb618e

Please re-open.

**Comment by jastevenson303** [comment]
Whenever the mob has a velocity greater than zero, their defined jump sound is played.  I take it the green slime is stopping and starting movement rapidly, then.
