### ISSUE TITLE
Mobs do not attack with low roof.

### ISSUE THREAD

**Issue by BrunoMine** [tenplus1/mobs_redo#31]
I created a mob that live in a hut with only two blocks of ceiling height, it is not possible to attack under these conditions.

The reason is that the line of sight is being calculated incorrectly in the API.
1.5 is added at the height of the mob and player's line of sight.

1723| [`p2.y = p2.y + 1.5`](https://github.com/tenplus1/mobs_redo/blob/master/api.lua#L1723)
1724| [`s2.y = s2.y + 1.5`](https://github.com/tenplus1/mobs_redo/blob/master/api.lua#L1724)
1725|
1726| [`if line_of_sight_water(self, p2, s2) == true then`](https://github.com/tenplus1/mobs_redo/blob/master/api.lua#L1726)

![Mod and player in a tight environment](https://cloud.githubusercontent.com/assets/7986261/21482875/deb4e09a-cb60-11e6-8980-15396aab788d.png)

**Comment by tenplus1** [comment]
Fixed.

**Comment by BrunoMine** [comment]
The error still persists.

Some situations are weird where the problem still occurs (screenshots).

Used mod:
https://forum.minetest.net/viewtopic.php?t=15382


![erro-2](https://cloud.githubusercontent.com/assets/7986261/21486495/c883176a-cb9c-11e6-8152-2baf1d096122.png)
![erro-1](https://cloud.githubusercontent.com/assets/7986261/21486637/144e7516-cb9f-11e6-9697-e4dab8e21af0.png)
![erro-3](https://cloud.githubusercontent.com/assets/7986261/21486639/14554f30-cb9f-11e6-94b4-957fa943f563.png)
![erro-4](https://cloud.githubusercontent.com/assets/7986261/21486638/1454432e-cb9f-11e6-8f0d-e5bf1c88ae85.png)

**Comment by tenplus1** [comment]
Any mobs I placed inside 2 high room found me and attacked without trouble, even dungeon masters...  Check collisionbox around your new mob and registry settings.

**Comment by BrunoMine** [comment]
I'm using exactly the same collisionbox as you.

[My npc](https://github.com/BrunoMine/sociedades/blob/master/sunos/npc/npc.lua#L48)
[Your npc](https://github.com/tenplus1/mobs_npc/blob/master/npc.lua#L21)

**Comment by tenplus1** [comment]
I cannot reproduce the error, I make a 2 high building and use '/spawnentity mobs:npc' to spawn a not-owned npc into the building which when punched attacks me...  I also test with sand monsters and they find and attack without a problem.

**Comment by BrunoMine** [comment]
I studied the problem. I placed an evidence of founded objects.
`if pos_w then minetest.chat_send_all(minetest.get_node(pos_w).name) end`

![erro-3](https://cloud.githubusercontent.com/assets/7986261/21571399/1d9d5e74-ceb6-11e6-9677-58f577f8dd85.png)
![erro](https://cloud.githubusercontent.com/assets/7986261/21571403/2bef59c8-ceb6-11e6-9455-af1cc3b0b769.png)
![erro-2](https://cloud.githubusercontent.com/assets/7986261/21571405/3229f26c-ceb6-11e6-85c5-97468af315ed.png)

**Comment by BrunoMine** [comment]
Two things are necessary to definitely fix this problem.
1) Ignore decorative nodes
2) Adjust line of sight (the line of sight can collide with objects that do not affect the attack, it may be necessary to analyze more than a single line of sight, for example, for the feet, and for the head of the player)

What are you about?

**Comment by tenplus1** [comment]
Line of sight ends when a node is in the way, I only managed to fix this with water mobs because I can always check for water, but decorative/walkthrough nodes are more difficult.
