### ISSUE TITLE
Documentation: Mistakes and missing info

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#85]
This is a list of possible mistakes and missing bits of documentation I found in `api.txt`:

`mobs:register_mob`:
* [x] `type`: The meaning of the 3 possible values is undefined **(important!)**
* [x] `walk_chance`: Undefined value range
* [x] `follow`: Does not mention that this also affects `feed_tame`
* [x] `view_range`: Typo near end of line
* [x] `damage`: Vague description. Which kind of damage? Melee? Projectiles?
* [x] `recovery_time`: Missing time unit
* [x] `armor`: Probably incorrect documentation; I have seen much larger numbers in practice
* [x] `fall_speed`: Not sure about this. Are the value limits still correct? As the function has been changed lately. Tick off if this is okay
* [x] `custom_attack`: It is not clear when exactly a custom attack is triggered and for which attack types this works
* [x] `on_blast`: This is probably not limited to TNT only
* [x] `arrow`: It is not clear if the arrow entity must follow some rules or if really *any* entity is permitted as arrow (even those added with `minetest.register_entity`)

Functions:
* [x] `mobs:register_egg`: 5th parameter is missing in header
* [x] `mobs:feed_tame`: 5th parameter is missing in header

`mobs:fly`, `mobs:drive`:
* [x] `move_animation`: No full list of allowed values
* [x] `stand_animation`: No full list of allowed values

Other:
* [x] `self.v2`: Useless explanation
* [x] Internal mob variables like `self.horny`, `self.health`, `self.gotten`, etc.: The documentation has duplicated them in two places somewhat inconsistently (Search for “The mob api also has some preset variables (…)” and “Useful Internal Variables”)

Tick off the entries as you go. :smiley:

**Comment by tenplus1** [comment]
Fixed.

**Comment by Wuzzy2** [comment]
Thanks!
But `move_animation` and `stand_animation` are missing something:

>    'move_animation' string containing name of pre-defined animation e.g. "walk" or "fly" etc.
>    'stand_animation' string containing name of pre-defined animation e.g. "stand" or "blink" etc.

This is still not a **complete** list of allowed values, therefore only of limited use.

**Comment by tenplus1** [comment]
Animation is detailed below on line 119 of the api.txt and shows settings for start frame, end frame, speed and loop...  The move and stand animations for flying/riding only requires the actual name of the animation itself.

**Comment by Wuzzy2** [comment]
Well, maybe I did not know the animation names are the same as the names in the `animation` table, minus suffix.
This was not obvious, so this fact should be explicitly mentioned.

Just say that the names are the same as in the `animation`, but without the underscore suffix. Then it should be OK. Unless I'm wrong.

**Comment by tenplus1** [comment]
Amended.

**Comment by Wuzzy2** [comment]
Thanks!
Everything is fine now. :+1:
